### ISSUE TITLE
exporter_name is not defined

### ISSUE THREAD

**Issue by joemontibello** [unt-libraries/catalog-api#15]
Getting this error when I go to Trigger New Export > Load all registered III record types into Solr > Filter data by: None (Full Export). The interface gave me an easy way to share this on dpaste.com, so here's the fuller error message:

http://dpaste.com/3289WSR

Not sure if this is really a problem with the software or something that I'm doing wrong. Let me know if I can test something, change settings, etc.

Take care,
Joe M.

**Comment by jthomale** [comment]
Hi Joe, apologies for taking a few days to get to this--I had GitHub notifications going to an email folder I wasn't paying attention to. I've reorganized so notifications on my projects go to a folder I'll actually check. :-)

Anyway, would you mind pulling down branch issue-15 and checking to see if that fixes the problem? Thanks!

**Comment by joemontibello** [comment]
Hi,

No worries – I've really just been testing with this, nothing's urgent. But I did pull down branch 15 and merge it into my local code, and I'm not seeing that error anymore!

Thank you!
Joe M.
