### ISSUE TITLE
Move base tests to pytest

### ISSUE THREAD

**Issue by jason-ellis** [unt-libraries/catalog-api#40]
Tests in the `base` app should use `pytest` like the other apps do, but we need to make sure that Travis CI doesn't run them. Also, may want to keep them out of the "all" test collection by default, should only be run when flagged.

A warning is produced in `create_field_test` when a field does not exist (`ObjectDoesNotExist`). Unittest prints the warning as soon as it's encountered, while pytest has a warning summary at the end. The warning summary only shows 1 warning, even though 5 of the same are encountered. Maybe need to find a way to display all 5 or indicate in the message that this isn't the only field that was missing.

**Comment by jthomale** [comment]
Done, as of merging PR #48 into master. The tests were moved into `base.tests.test_databases` and are run regularly via pytest.
